### ISSUE TITLE
Ensure the plugin works when imported

### ISSUE THREAD

**Issue by jakubfiala** [ecosia/vue-safe-html#15]

**Comment by axlwaii** [comment]
@jakubfiala @LostCrew I took a look at this issue. 

I managed to use the plugin in a new created Vue 2 App.
It also works within our nuxt setup by adding:
```json
{ src: '~~/common/nuxt/plugins/safe-html', mode: 'client' }
```
to the `plugins` sections inside `common/nuxt/config.js`

To close this issue do you think it is enough to document how to integrate `vue-safe-html` in a nuxt app?

**Comment by jakubfiala** [comment]
awesome! I think that sounds good, it's worth accounting for Nuxt in the readme because it's also a way to help Nuxt by making users aware of it :)

**Comment by LostCrew** [comment]
Yes, let's add a section for it :+1
