### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by jakubfiala** [ecosia/vue-safe-html#16]

**Comment by axlwaii** [comment]
I think in order to publish we need to align on a name:
@LostCrew suggested `vue-strip-html` which seems to be still available and describes much better what the package does. It is also still available as a name https://www.npmjs.com/search?q=vue-strip-html

**Comment by jakubfiala** [comment]
@axlwaii I'd be happy with either name! `-strip-html` sounds good

**Comment by LostCrew** [comment]
@jakubfiala @axlwaii Done! 🎉
