### ISSUE TITLE
Decide who will maintain the package

### ISSUE THREAD

**Issue by jakubfiala** [ecosia/vue-safe-html#22]

**Comment by LostCrew** [comment]
@jakubfiala @axlwaii Us co-maintainers until some better maintenance framework is discussed?

**Comment by axlwaii** [comment]
I think we should have at least two main maintainers. Happy to be one of them.

**Comment by LostCrew** [comment]
Same, I enjoy this — so far!

**Comment by axlwaii** [comment]
We decided to split ownership and maintenance between @LostCrew @jakubfiala @axlwaii
