### ISSUE TITLE
Allows all tags starting with...

### ISSUE THREAD

**Issue by nkoehring** [ecosia/vue-safe-html#48]
**Describe the bug**
The regular expression used to sanitize is filtering for everything that starts with `allowedTag`, optionally followed by something  until a closing `>`. This allows some tags to slip through, for example `<blockquote>` if only `<b>` is allowed or even worse `<script>` if only `<s>` should be allowed. 

**To Reproduce**
https://codesandbox.io/s/stoic-field-kbpif?file=/src/index.js

**Expected behavior**
If a tag is allowed, it should not implicitly allow any other tag.

**Comment by JBustin** [comment]
Hello

Thanks for the share of code.
Have you got any idea to fix that ?

Regards

**Comment by nkoehring** [comment]
Hi @JBustin . I'm not at the company anymore since a while so I might remember things wrong. But is it somehow possible to use spaces as additional delimiter? The only actually save way would be using an actual parser tough. There are quite some HTML parser implementations already.

**Comment by JBustin** [comment]
Thanks @nkoehring for your fast feedback.
I have made my own directive based on https://github.com/apostrophecms/sanitize-html to support this case.

**Comment by LostCrew** [comment]
@nkoehring Fixed in https://github.com/ecosia/vue-safe-html/releases/tag/v2.2.0

**Comment by nkoehring** [comment]
Nice! I see you're using word boundary (`\w`) now, which makes sense. The Regular Expression looks a bit crazy now, but great to see it being developed further!
