### ISSUE TITLE
Questionable forward slash in Regex

### ISSUE THREAD

**Issue by fmeyertoens** [ecosia/vue-safe-html#67]
I am wondering about the forward slash in the middle of this regular expression and can't figure out its meaning. The slash should indicate start and end of a regex but this can't be the case here.
https://github.com/ecosia/vue-safe-html/blob/56d583d8a3bf31e4b2f900a0748cb477ac23a4dd/src/utils.js#L10
regex101.com highlights this as a pattern error: https://regex101.com/r/xdfjJj/1
I'd understand if this was `\/` because this would match the slash in a closing tag but what does `s*` do then?

**Comment by axlwaii** [comment]
Thank you for reaching out. 

The line:
https://github.com/ecosia/vue-safe-html/blob/940b79ae83371db0184412d306f42992c9dcbfa1/src/utils.js#L10 
Is the regular expression string which will be transformed into a valid regular expression using `new RegExp`:
https://github.com/ecosia/vue-safe-html/blob/940b79ae83371db0184412d306f42992c9dcbfa1/src/utils.js#L12

Taking the example you are provided:
```js
const expression = '<(?!((?:/s*)?(?:header|p|div)))([^>])+>';
const regExp = new RegExp(expression, 'g');
console.log(regExp);
> /<(?!((?:\/s*)?(?:header|p|div)))([^>])+>/g
```
So `/s` will actually be transformed into `/\s`: https://regex101.com/r/fAE9e4/1

`/\s*` will match any whitespace characters.  

I hope that answers your question - We will make sure to add some more documentation to the regular expressions with the next update.

**Comment by fmeyertoens** [comment]
The first part I now understand, i.e. the slash is automatically escaped. The relevant part of the spec seems to be https://tc39.es/ecma262/multipage/text-processing.html#sec-escaperegexppattern. I didn't know about this behavior.
This means, as you correctly wrote (at first), that the regular expression now reads as: `...\/s*...`. (You switched the characters later in your answer). It therefore matches the backslash character followed by any number of `s` characters but not whitespace. This can be verified with the following tests in "utils.test.js":
```js
...
    it('Current behavior which seems strange because it matches multiple s characters', () => {
      const allowedTags = ['p'];
      const given = '<sp>Test1</sp><sssp>Test2</sssp>';
      const expected = 'Test1</sp>Test2</sssp>';
      expect(utils.sanitizeHTML(given, allowedTags)).toBe(expected);
    });

    it('Probably the desired behavior which currently fails but matches whitespace', () => {
      const allowedTags = ['p'];
      const given = '<p>Test1</ p><p>Test2</   p>';
      const expected = '<p>Test1</ p><p>Test2</   p>';
      expect(utils.sanitizeHTML(given, allowedTags)).toBe(expected);
    });
...
```
The first test passes and the second one fails. When I modify the RegExp in "utils.js" to `.../\\s*...`, the first test correctly fails and the second one passes.

**Comment by axlwaii** [comment]
@fmeyertoens Thanks a lot for your investigation and time you put into the tests, we will look into this a provide a fix.

**Comment by LostCrew** [comment]
@fmeyertoens Should be now fixed, try it out: https://github.com/ecosia/vue-safe-html/releases/tag/v2.2.0
