### ISSUE TITLE
Node 16 compatibility

### ISSUE THREAD

**Issue by tomsq** [ecosia/vue-safe-html#68]
Hello, 
is there a reason why this package doesn't work with the current LTS version of Node (16.13.1)?

**Comment by LostCrew** [comment]
We've just upgraded the package.json node engine https://github.com/ecosia/vue-safe-html/blob/main/package.json#L22. I'll cut a 1.2.0 GitHub release to document it

**Comment by VincentDauliac** [comment]
same problem now with node 17. What's the purpose of using the engine property in package.json ? Isn't it a pain to keep it up to date on each new nodejs release ?
