### ISSUE TITLE
The tag of <a> no attribute ?

### ISSUE THREAD

**Issue by wangsrGit119** [ecosia/vue-safe-html#85]
**Describe the bug**
when I use thi component，I wang to use <a> in text ，but the result without any attribut
**To Reproduce**
1.  var text = `<a href="http://www.google.com" target="_blank">http://www.google.com</a> xxxx hhhhhh`
2.
```html
<div v-safe-html="text"></div>
```

3. 
```html
<a>http://www.google.com</a>xxxx hhhhhh
```

**Expected behavior**

```html
<a href="http://www.google.com" target="_blank">http://www.google.com</a> xxxx hhhhhh

```

**Comment by craigiswayne** [comment]
I suspect this package removes all attributes from any tag

I haven't thoroughly tested this, but what I have seen is that the `class` attribute is being stripped from my div tag when it is generated

something like
```
<div class="container">hello world</div>
```

renders

```
<div>hello world</div>
```

**Comment by Kamsou** [comment]
Hello guys, i have the same problem. Did you find another way to do it?

**Comment by mreduar** [comment]
> Hello guys, i have the same problem. Did you find another way to do it?
> 
> * With `vue-dompurify-html` its okay

@Kamsou Thank you for the suggestion!

**Comment by walkerz88** [comment]
Hi! You can use allowedAttributes property, like:
`allowedAttributes: ['title', 'class', 'href']`
it is mentioned in manual

**Comment by craigiswayne** [comment]
I rate we can close this now due to changes in the codebase

as @walkerz88 pointed out, you can now do the following:

```typescript
Vue.use(VueSafeHTML, {
  allowedTags: ['a'],
  allowedAttributes: ['href', 'target'],
});
```

```html
var text = <a href="http://www.google.com" target="_blank">http://www.google.com</a> xxxx hhhhhh
```

**Note:** specifiying just `allowedTags` is not enough, you'll need to also specifiy `allowedAttributes`

---

See this commit for changes https://github.com/ecosia/vue-safe-html/commit/4b957f5049f79cfe346eb5690e9ef5374796122d (2 weeks ago)
